In [2]:
import pandas as pd

file_path = '소상공인시장진흥공단_전국 온누리상품권 가맹점 현황_20250731 (1).csv'
df = pd.read_csv(file_path)
df.head()

,가맹점명,소속 시장명(또는 상점가),소재지,취급품목,지류형 가맹 여부,디지털형 가맹 여부,등록년도
0,초마맨1981,권율 골목형상점가,경기,짜장면 짬뽕 탕수육,Y,Y,2025
1,못난이 꽈배기,"일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)",광주,꽈배기 도너츠,Y,Y,2025
2,일곡열쇠철물,"일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)",광주,열쇠,Y,Y,2025
3,참새 방앗간,권율 골목형상점가,경기,육전 새우전,Y,Y,2025
4,뿔라헤어컷,"일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)",광주,미용,Y,Y,2025

In [5]:
df.drop([0,1])
df.drop('가맹점명',axis=1)

,소속 시장명(또는 상점가),소재지,취급품목,지류형 가맹 여부,디지털형 가맹 여부,등록년도
0,권율 골목형상점가,경기,짜장면 짬뽕 탕수육,Y,Y,2025
1,"일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)",광주,꽈배기 도너츠,Y,Y,2025
2,"일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)",광주,열쇠,Y,Y,2025
3,권율 골목형상점가,경기,육전 새우전,Y,Y,2025
4,"일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)",광주,미용,Y,Y,2025
...,...,...,...,...,...,...
150536,단양구경시장(단양인정시장),충북,식잡,Y,Y,2010
150537,단양구경시장(단양인정시장),충북,"일반한식,생닭",Y,Y,2010
150538,단양구경시장(단양인정시장),충북,일반미용업,Y,Y,2010
150539,단양구경시장(단양인정시장),충북,한식점업,Y,Y,2010
150540,단양구경시장(단양인정시장),충북,분식,Y,Y,2010

In [10]:
df['등록년도'].unique()
df['등록년도'].isin( [2020,2025] )

0          True
1          True
2          True
3          True
4          True
          ...
150536    False
150537    False
150538    False
150539    False
150540    False
Name: 등록년도, Length: 150541, dtype: bool